Refactor
onmodulus/logger pull request #15
Opened 2017-01-27 03:02 UTC by jackboberg

This started as an attempt to solve the issue where every logger attached more EventEmiter listeners, leading to memory leaks:

`(node:15) Warning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit`

..in the end I accidentally the whole module. 👍

2017-01-27 03:04 UTC, jackboberg commented
I'll need to update the `README` around exception logging, which is now transparent to the user and only requires a `EXCEPTION_LOG` environment variable (that is a writeable path).

2017-01-30 15:38 UTC, theworkflow commented
@jackboberg would love to go over this PR.

2017-02-06 20:17 UTC, bsatrom approved these changes

2017-02-06 20:17 UTC, bsatrom commented on README.md
>  # Modulus logger
Modulus --> Xervo?

2017-02-06 20:17 UTC, theworkflow requested changes

2017-02-06 20:17 UTC, theworkflow commented on README.md
>  # Modulus logger
update name

2017-02-06 21:37 UTC, jackboberg commented
fixed README name

2017-02-09 21:45 UTC, theworkflow approved these changes

2017-02-09 21:46 UTC, merged